apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: user-activity-logs
  namespace: kafka
  labels:
    strimzi.io/cluster: streaming-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 600000

