apiVersion: v1
kind: Service
metadata:
  name: was-service-external
  namespace: was
spec:
  type: NodePort
  selector:
    app: was
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
      name: http

